### ISSUE TITLE
New: macOS icon!

### ISSUE THREAD

**Issue by cdevroe** [cdevroe/switcheroo#3]
Hand drawn by a human preferred.

**Comment by zhenyi** [comment]
Just added a new icon in https://github.com/cdevroe/switcheroo/commit/3153361af2a87c414a7fbca1033b2f3be7fb868c.

**Comment by cdevroe** [comment]
@zhenyi Yay! I wonder if we should also roll in the code you wrote related to the Sequoia issues I was seeing?
